### ISSUE TITLE
CustomTargetingService performCustomTargetingValueAction

### ISSUE THREAD

**Issue by TarSzator** [ShinyAds/node-google-dfp#12]
I'm trying to use this action, but I can't find a way to handle the abstract customTargetingValueAction.
There I must set the xsi:type to DeleteCustomTargetingValues somehow.
Can someone help me with this or is it not possible to handle abstract elements?

**Comment by ajsouza** [comment]
This just means that your JSON should be something like this;
```
customTargetingValueAction : { 'xsi:type': 'DeleteCustomTargetingValues' }
```

**Comment by TarSzator** [comment]
It worked. Thanks for the help.

**Comment by sapirm290** [comment]
Second one. thanks!
