### ISSUE TITLE
Code:502 error

### ISSUE THREAD

**Issue by stavrosf4** [ShinyAds/node-google-dfp#13]
Hello world!
First of all thanks to anyone involved for this.. It's an excellent tool that has helped me greatly.
Over the last couple of weeks I get an error with code 502, every now and then and need to restart my application. Has anyone noticed anything similar or knows of any workarounds?

Thanks again,
Stavros

**Comment by ajsouza** [comment]
That error shouldn't crash your application (BAD GATEWAY). We do get it on occasion as well as SERVER ERROR and lately WSDL PARSE ERROR. All of these error you should be able to treat with the err return from the callback

**Comment by stavrosf4** [comment]
Thanks for the immediate response @ajsouza !
Will do that.. Cheers!
