### ISSUE TITLE
cannot assign to readonly property targetNSAlias on node v0.12

### ISSUE THREAD

**Issue by Batornator** [ShinyAds/node-google-dfp#14]
After upgrading to node v0.12, I am getting an error. After som research I believe this is due to the version of node-soap being use. I noticed that the package.json for this module reqquires soap 0.5, wheras the latest versionis 0.9.3 and looking through the oull request/issue history on the soap module I see that a fix for this issue was submitted and merged some time ago. I think an update to this modules dependencies is needed, I have tried just a straight upgrade on a fork but I then get some soap errors. I was wondering if you could give me some pointers on fixing this or perhaps have a look yourself?

The error on node v0.12 using soap v0.5 is below: 

Cannot assign to read only property 'targetNSAlias' of TeamAccessType|xsd:string|NONE,READ_ONLY,READ_WRITE date=Tue Jul 07 2015 10:59:45 GMT+0100 (BST), pid=39975, uid=501, gid=20, cwd=/Users/Sam/Documents/Work/salesknowledge/sales-knowledge-api, execPath=/usr/local/Cellar/node/0.12.0_1/bin/node, version=v0.12.0, argv=[node, /usr/local/bin/sails, lift], rss=183975936, heapTotal=153554176, heapUsed=116197872, loadavg=[2.75537109375, 2.11328125, 1.96044921875], uptime=700397, trace=[column=28, file=/Users/Sam/Documents/Work/salesknowledge/sales-knowledge-api/node_modules/node-google-dfp/node_modules/soap/lib/wsdl.js, function=ElementElement.description, line=819, method=description, native=false, column=29, file=/Users/Sam/Documents/Work/salesknowledge/sales-knowledge-api/node_modules/node-google-dfp/node_modules/soap/lib/wsdl.js, function=AllElement.description.SequenceElement.description [as description], line=858, method=description.SequenceElement.description [as description], native=false, column=20, file=/Users/Sam/Documents/Work/salesknowledge/sales-knowledge-api/node_modules/node-google-dfp/node_modules/soap/lib/wsdl.js, function=ComplexTypeElement.description, line=765, method=description, native=false, column=46, file=/Users/Sam/Documents/Work/salesknowledge/sales-knowledge-api/node_modules/node-google-dfp/node_modules/soap/lib/wsdl.js, function=ElementElement.description, line=817, method=description, native=false, column=29, file=/Users/Sam/Documents/Work/salesknowledge/sales-knowledge-api/node_modules/node-google-dfp/node_modules/soap/lib/wsdl.js, function=AllElement.description.SequenceElement.description [as description], line=858, method=description.SequenceElement.description [as description], native=false, column=20, file=/Users/Sam/Documents/Work/salesknowledge/sales-knowledge-api/node_modules/node-google-dfp/node_modules/soap/lib/wsdl.js, function=ComplexTypeElement.description, line=765, method=description, native=false, column=31, file=/Users/Sam/Documents/Work/salesknowledge/sales-knowledge-api/node_modules/node-google-dfp/node_modules/soap/lib/wsdl.js, function=ElementElement.description, line=843, method=description, native=false, column=33, file=/Users/Sam/Documents/Work/salesknowledge/sales-knowledge-api/node_modules/node-google-dfp/node_modules/soap/lib/wsdl.js, function=MessageElement.postProcess, line=500, method=postProcess, native=false, column=13, file=/Users/Sam/Documents/Work/salesknowledge/sales-knowledge-api/node_modules/node-google-dfp/node_modules/soap/lib/wsdl.js, function=OperationElement.postProcess, line=602, method=postProcess, native=false, column=11, file=/Users/Sam/Documents/Work/salesknowledge/sales-knowledge-api/node_modules/node-google-dfp/node_modules/soap/lib/wsdl.js, function=PortTypeElement.postProcess, line=622, method=postProcess, native=false, column=14, file=/Users/Sam/Documents/Work/salesknowledge/sales-knowledge-api/node_modules/node-google-dfp/node_modules/soap/lib/wsdl.js, function=BindingElement.postProcess, line=636, method=postProcess, native=false, column=15, file=/Users/Sam/Documents/Work/salesknowledge/sales-knowledge-api/node_modules/node-google-dfp/node_modules/soap/lib/wsdl.js, function=ServiceElement.postProcess, line=671, method=postProcess, native=false, column=26, file=/Users/Sam/Documents/Work/salesknowledge/sales-knowledge-api/node_modules/node-google-dfp/node_modules/soap/lib/wsdl.js, function=null, line=971, method=null, native=false, column=12, file=/Users/Sam/Documents/Work/salesknowledge/sales-knowledge-api/node_modules/node-google-dfp/node_modules/soap/lib/wsdl.js, function=WSDL._processNextInclude, line=1022, method=_processNextInclude, native=false, column=8, file=/Users/Sam/Documents/Work/salesknowledge/sales-knowledge-api/node_modules/node-google-dfp/node_modules/soap/lib/wsdl.js, function=WSDL.processIncludes, line=1052, method=processIncludes, native=false, column=10, file=/Users/Sam/Documents/Work/salesknowledge/sales-knowledge-api/node_modules/node-google-dfp/node_modules/soap/lib/wsdl.js, function=null, line=961, method=null, native=false], stack=[TypeError: Cannot assign to read only property 'targetNSAlias' of TeamAccessType|xsd:string|NONE,READ_ONLY,READ_WRITE,     at ElementElement.description (/Users/Sam/Documents/Work/salesknowledge/sales-knowledge-api/node_modules/node-google-dfp/node_modules/soap/lib/wsdl.js:819:28),     at AllElement.description.SequenceElement.description [as description] (/Users/Sam/Documents/Work/salesknowledge/sales-knowledge-api/node_modules/node-google-dfp/node_modules/soap/lib/wsdl.js:858:29),     at ComplexTypeElement.description (/Users/Sam/Documents/Work/salesknowledge/sales-knowledge-api/node_modules/node-google-dfp/node_modules/soap/lib/wsdl.js:765:20),     at ElementElement.description (/Users/Sam/Documents/Work/salesknowledge/sales-knowledge-api/node_modules/node-google-dfp/node_modules/soap/lib/wsdl.js:817:46),     at AllElement.description.SequenceElement.description [as description] (/Users/Sam/Documents/Work/salesknowledge/sales-knowledge-api/node_modules/node-google-dfp/node_modules/soap/lib/wsdl.js:858:29),     at ComplexTypeElement.description (/Users/Sam/Documents/Work/salesknowledge/sales-knowledge-api/node_modules/node-google-dfp/node_modules/soap/lib/wsdl.js:765:20),     at ElementElement.description (/Users/Sam/Documents/Work/salesknowledge/sales-knowledge-api/node_modules/node-google-dfp/node_modules/soap/lib/wsdl.js:843:31),     at MessageElement.postProcess (/Users/Sam/Documents/Work/salesknowledge/sales-knowledge-api/node_modules/node-google-dfp/node_modules/soap/lib/wsdl.js:500:33),     at OperationElement.postProcess (/Users/Sam/Documents/Work/salesknowledge/sales-knowledge-api/node_modules/node-google-dfp/node_modules/soap/lib/wsdl.js:602:13),     at PortTypeElement.postProcess (/Users/Sam/Documents/Work/salesknowledge/sales-knowledge-api/node_modules/node-google-dfp/node_modules/soap/lib/wsdl.js:622:11),     at BindingElement.postProcess (/Users/Sam/Documents/Work/salesknowledge/sales-knowledge-api/node_modules/node-google-dfp/node_modules/soap/lib/wsdl.js:636:14),     at ServiceElement.postProcess (/Users/Sam/Documents/Work/salesknowledge/sales-knowledge-api/node_modules/node-google-dfp/node_modules/soap/lib/wsdl.js:671:15),     at /Users/Sam/Documents/Work/salesknowledge/sales-knowledge-api/node_modules/node-google-dfp/node_modules/soap/lib/wsdl.js:971:26,     at WSDL._processNextInclude (/Users/Sam/Documents/Work/salesknowledge/sales-knowledge-api/node_modules/node-google-dfp/node_modules/soap/lib/wsdl.js:1022:12),     at WSDL.processIncludes (/Users/Sam/Documents/Work/salesknowledge/sales-knowledge-api/node_modules/node-google-dfp/node_modules/soap/lib/wsdl.js:1052:8),     at /Users/Sam/Documents/Work/salesknowledge/sales-knowledge-api/node_modules/node-google-dfp/node_modules/soap/lib/wsdl.js:961:10]

Thanks

**Comment by ajsouza** [comment]
Hi @Batornator, 
One doubt looking at what you have posted, the error message seems to suggest you're trying to set a field that's read only [TeamAccessType ?]. We have had issues with the soap module in the past, I did have to use a lower version because the newer version gave me issue in setting one of the parameters of the header -but I am not sure this is the issue from the error posted.

**Comment by Batornator** [comment]
Thanks for the pointer. I will have to look into that as the code was written by another team member I just happened to run into trouble with it after upgrading to node 0.12. 



—
