### ISSUE TITLE
Soap version 0.5 generates error on recent versions of node

### ISSUE THREAD

**Issue by sudsy** [ShinyAds/node-google-dfp#15]
Current 0.5 soap library 

Throws an error on recent versions of node:

See: https://github.com/vpulim/node-soap/issues/567

```
node_modules/soap/lib/wsdl.js:819
        elem.targetNSAlias = type.namespace;
                           ^
TypeError: Cannot assign to read only property 'targetNSAlias' of ExportFormat|xsd:string|TSV,CSV_EXCEL,CSV_DUMP,XML,XLSX
```

Updating to a more recent soap version removes this error

**Comment by ajsouza** [comment]
I believe this error is corrected with the latest fixes. Let me know.

**Comment by sudsy** [comment]
Looks Good. I tested it using the git repo as a dependency. Let me know when the version is updated and I can change my dependency to an npm one.

**Comment by ajsouza** [comment]
Ok. It's published

**Comment by sudsy** [comment]
Cheers!
