### ISSUE TITLE
DfpUser#getService callback does not follow errback style

### ISSUE THREAD

**Issue by ahaurw01** [ShinyAds/node-google-dfp#17]
There doesn't appear to be any way to catch errors originating from service lookups. The callback to `DfpUser.prototype.getService` is invoked only with the service after the lookup is successful. It does not follow the typical node "errback" style used elsewhere in the library.

Errors are thrown at https://github.com/ShinyAds/node-google-dfp/blob/master/lib/DfpUser.js#L60 and https://github.com/ShinyAds/node-google-dfp/blob/master/lib/DfpUser.js#L66. As far as I can tell, there is no way to catch these errors?

**Comment by JuanCaicedo** [comment]
This is really cool, it also makes it possible to Promisify this library with Bluebird, which I was having to hack my way around before!

**Comment by ajsouza** [comment]
@JuanCaicedo thanks for feedback.
