### ISSUE TITLE
Error undefined:undefined (update soap)

### ISSUE THREAD

**Issue by JuanCaicedo** [ShinyAds/node-google-dfp#20]
I've previously gotten an error with the status code `undefined:undefined`. This is a problem inside `node-soap` and they've addressed it in [this commit](https://github.com/vpulim/node-soap/commit/605ec59130d020417d83ff0c6a8006951042acc1), which we should get by updating to v0.11.0.

I'm not sure if updating will have any breaking changes, but I can research, try it out, and then submit a PR.

**Comment by ajsouza** [comment]
Hi @JuanCaicedo that would be great. Our last update to node-soap was worried it could be a breaking change but turned out not to affect -at least did not have any feedback to suggest this was the case.

**Comment by JuanCaicedo** [comment]
It seems like there's no release currently that includes that commit. The most recent release was 17 days ago and the commit was shortly after that. Maybe we could instead depend on a specific commit, until we're able to update to the new release. I'll make a PR for that, in case it seems like a good approach to you @ajsouza. I can also keep an eye on node-soap and make an another PR when there is a release.

**Comment by ajsouza** [comment]
@JuanCaicedo can you give me an example of a call that causes this? [I think I have seen this issue before and DFP API docs seems to have a suggested fix] -it is easier to understand if I can walk-through a sample call.

**Comment by JuanCaicedo** [comment]
An easy way to recreate it is to try to create a line item creative association which already exists. You will need the unique id for the line item and the unique id for the creative, which I think you can find by opening an the association in the DFP site and inspecting the url. 

service —`LineItemCreativeAssociationService`
method — `createLineItemCreativeAssociations`
params —
```javascript
{
  lineItemCreativeAssociations: [{
    lineItemId: '<lineItemId>',
    creativeId: '<creativeId>'
  }]
}
```

**Comment by JuanCaicedo** [comment]
@ajsouza Were you able to see reproduce that error?
