### ISSUE TITLE
rounding / float problems using Dfp.Money

### ISSUE THREAD

**Issue by kitwestneat** [ShinyAds/node-google-dfp#22]
we price things in cents, and so to use Dfp.Money, we need to divide by 100. On some values, the JS floats represents it in a value that's illegal to DFP. Like 250 became 2.49999999999, which became microAmount: 2499999.999. So it would be nice if Dfp.Money used Math.round.

**Comment by ajsouza** [comment]
Hey @kitwestneat can you give me an example [code] of when this occurs? I just tried to write a test, but could not see the error you're seeing -so not sure I understand. My sample test (it passes).
```javascript
   describe(".Money", function () {
    it("should convert money to DFP micro amounts", function () {
      var dfp_statement = new DfpUtils.Money(250/100, 'CAD'),
        expected_query  = {
          currencyCode  : 'CAD',
          microAmount   : 2500000
        };
      expect(dfp_statement.currencyCode).toBe(expected_query.currencyCode);
      expect(dfp_statement.microAmount).toBe(expected_query.microAmount);
    });
  });
```

**Comment by kitwestneat** [comment]
Sure. I'm not sure if it is JS engine dependent, but it's a pretty common
floating point problem in general (http://floating-point-gui.de/). Here's
an example that works on my version of node:

> var dfp = require('node-google-dfp')
undefined
> dfp.Money(418/100, 'USD')
{ currencyCode: 'USD',
  microAmount: 4179999.9999999995 }

I found it by doing a for loop from 1 to 500.

**Comment by ajsouza** [comment]
Ok, managed to recreate the error.

**Comment by ajsouza** [comment]
Ok. That's fixed.

**Comment by kitwestneat** [comment]
Awesome, thanks!
