### ISSUE TITLE
could you push to merge into `google/google-api-nodejs-client`

### ISSUE THREAD

**Issue by c0b** [ShinyAds/node-google-dfp#27]
we want to write dfp applications in nodejs but they have limited client libraries support officially [1], only java, php, python, ruby not what we want;

this project looks good, but with 3rd party implementation my only concern is future maintainability, what if they break something and how soon can this library fix up? what if this library author becomes inactive and out of maintenance ? as I think, to provide more choices for developers for dfp should be google's responsibility, although the official Google DFP [2] is not doing, but there is [1] google api nodejs client can be seen as part of semi-official , could you try to push / merge into the project?

1. https://github.com/google/google-api-nodejs-client
2. https://developers.google.com/doubleclick-publishers/docs/clients

**Comment by ajsouza** [comment]
Taking a look at feasibility of doing this.

**Comment by c0b** [comment]
see my comments at `v201505` almost deprecated, how soon will this likely to get an update and can we push nodejs api get somewhat official support from someone @google

https://github.com/ShinyAds/node-google-dfp/commit/1b1c3ecaf69d883e35ec87b3ea87e5c54ec3a743#commitcomment-17017959
https://groups.google.com/d/msg/google-doubleclick-for-publishers-api/mj-UJzX8-gE/3igKLNIkUMcJ

**Comment by ajsouza** [comment]
@c0b - If you take a look at the code, you should notice that version can be supplied as a parameter. We avoid constant version in the base code as changes from 1 version to another could break other dev's code.
```javascript
var dfpSetup = new DfpClass('MyNetworkCode', 'mySuperDuperAwesomeApp', 'v201602');
```
A couple of points on the Google front -
1. If you look at the links you have provided you will notice that contributing to Google's NodeJS repo requires you adhere to their coding guidelines etc... I don't plan on moving on this quick. You're welcome to fork the repo and contribute to the Google repo.
2. Although there's an excellent argument in merging this in the Google repo, there's also an equally good case for having it separate -again I don't plan on spending time prioritizing this.
3. I suspect DoubleClick has a reason for not building support into main Google node api -as in they may not want it there, it usually is absent as an integration in the Google Cloud API Manager. You may want to check [figure] this out first before even building against the main repo.
