### ISSUE TITLE
BASE_API_URL

### ISSUE THREAD

**Issue by TarSzator** [ShinyAds/node-google-dfp#4]
It seems that the BASE_API_URL must be changed from https://www.google.com/apis/ads/publisher to https://ads.google.com/apis/ads/publisher.

After using the current version and getting a 404 I changed the BASE_API_URL to https://ads.google.com/apis/ads/publisher and it worked.

Can you please verify and change it.
Thanks

**Comment by TarSzator** [comment]
I tried to fork and commit a new branch with the changed BASE_API_URL but if got a permission denied error.

{code}
$ git push origin new-base-api-url
ERROR: Permission to ShinyAds/node-google-dfp.git denied to TarSzator.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
{code}

**Comment by grevory** [comment]
Thanks for the attempt. We can't check on this now, but I presume you are having this trouble because the user is a private organization.

Once we get a chance, we're quite busy now, we'll check into what is wrong. Thanks again.

**Comment by TarSzator** [comment]
Ok, thanks for the response.
Since I need the fork now I forked this repo to https://github.com/TarSzator/node-google-dfp-fork
I will remove it when your version is working for me again.

**Comment by ajsouza** [comment]
@TarSzator pushed a correction for this. Thanks.

**Comment by TarSzator** [comment]
I don't quite get the commit comment.
First I get the error with version 201411. Second you did not create a new version so I can't use it.

**Comment by ajsouza** [comment]
@TarSzator can you explain what you mean by new version? v201408 of DFP changed API endpoint, so if you're using v201411 this change should work.

**Comment by TarSzator** [comment]
That explaines the commit comment. I read it the other way around.

To the second point. It is good practis to change the version in the package.json when you change something in a node project and create a git tag with the same name.
You can use "npm version patch" for this. This will set the version in the package.json to 0.1.6 and create a tag in the repository with the name v0.1.6.
