### ISSUE TITLE
How do I get a refresh token?

### ISSUE THREAD

**Issue by HoraceShmorace** [ShinyAds/node-google-dfp#5]
Sorry, I'm not a OAuth2 expert.

**Comment by ajsouza** [comment]
Hi Horace,

    A good place to start is these 2 links https://developers.google.com/doubleclick-publishers/docs/authentication & https://developers.google.com/accounts/docs/OAuth2WebServer. There are different options for using OAuth, but if you're interested in refresh_token, most likely your service needs some form of offline access (refers to user not being online). There are basically 2 distinct processes, 1 the user authorizes you for this offline access & 2 you use the refresh_token received to access their DFP account. Both of these are well explained in the OAuth2WebServer.
